lambd: 100000                    # average count rate (counts/second)
total_time: 1                  # (seconds)
lag: 0                          # difference between idler and signal (picoseconds)
loss_signal: 0.1                # probability of not being detected for the signal photons
loss_idler: 0.1                 # probability of not being detected for the idler photons
dark_count_rate: 5000           # (counts/second)
dead_time: 1000               # (picoseconds)
jitter_fwhm: 100                # (picoseconds)
coincidence_interval: 1000      # (picoseconds)